### ISSUE TITLE
Build fails after nginx 1.23.0

### ISSUE THREAD

**Issue by peytonyip** [vislee/ngx_http_ipdb_module#12]
when try to build with  nginx 1.23.1,it fails

here are the error log:
```
        -o objs/ngx_http_ipdb_module_modules.o \
        objs/ngx_http_ipdb_module_modules.c
/usr/src/ngx_http_ipdb_module/ngx_http_ipdb_module.c: In function 'ngx_http_ipdb_variable':
/usr/src/ngx_http_ipdb_module/ngx_http_ipdb_module.c:620:14: error: assignment to 'ngx_array_t *' from incompatible pointer type 'ngx_table_elt_t **' {aka 'struct ngx_table_elt_s **'} [-Werror=incompatible-pointer-types]
  620 |         xfwd = &r->headers_in.x_forwarded_for;
      |              ^
/usr/src/ngx_http_ipdb_module/ngx_http_ipdb_module.c:622:58: error: passing argument 3 of 'ngx_http_get_forwarded_addr' from incompatible pointer type [-Werror=incompatible-pointer-types]
  622 |             (void) ngx_http_get_forwarded_addr(r, &addr, xfwd, NULL,
      |                                                          ^~~~
      |                                                          |
      |                                                          ngx_array_t *
In file included from src/http/ngx_http.h:36,
                 from /usr/src/ngx_http_ipdb_module/ngx_http_ipdb_module.c:7:
src/http/ngx_http_core_module.h:532:22: note: expected 'ngx_table_elt_t *' {aka 'struct ngx_table_elt_s *'} but argument is of type 'ngx_array_t *'
  532 |     ngx_table_elt_t *headers, ngx_str_t *value, ngx_array_t *proxies,
      |     ~~~~~~~~~~~~~~~~~^~~~~~~
```

**Comment by vislee** [comment]
@peytonyip  Yes，xfwd is using `ngx_table_elt_s ` instead of `ngx_array_t ` in nginx-1.23.0+，haved fix please try again。

**Comment by peytonyip** [comment]
it works. Thank you!
